version: '3'
services:
  gotify:
    image: gotify/server
    ports:
      - 'PORT_GOTIFY=${PORT}:80'
    environment:
      - 'GOTIFY_DEFAULTUSER_PASS=${GOTIFY_DEFAULTUSER_PASS}'
      - 'TZ=${TZ}'
    volumes:
      - './gotify_data:/app/data'

